apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/instance: demo
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: demo
spec:
  selector:
    app: demo
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8080
      